name: Release Desktop Application

on:
  push:
    branches: [ "configureGithubActions" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  publish:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: LessonPlanningSystem.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Todo: delete
          ref: 'configureGithubActions'
          fetch-depth: 0
      
      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Install dependencies
        run: dotnet restore

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Execute unit tests
        run: dotnet test --no-restore --verbosity normal

      - name: Build with dotnet
        run: dotnet build -c Release --no-restore
        
      - name: dotnet publish
        run: dotnet publish clients/LPS.Desktop -c Release -r win-x64 --sc true -o ${{env.DOTNET_ROOT}}/desktop_app -p:PublishSingleFile=true --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/desktop_app
